[package]
name = "poc-rscreen"
version = "0.1.0"
authors = ["bib0x"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssh = "0.8.0"
tokio = { version = "1.0", features = ["full"] }
clap = "3.0.0-beta.2"
